version: '3.9'
services:
  nest-api:
    image: asia-southeast2-docker.pkg.dev/numeric-advice-384613/fauzan-nest-dockerize/my-backend-infra
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - "80:4000"
      - "443:4000"
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - database
  database:
    image: postgres:13
    container_name: my-backend-infra-database
    hostname: database
    restart: always
    ports:
      - "6500:5432"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: