version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - database
  database:
    image: postgres:13
    container_name: postgres
    hostname: database
    restart: always
    ports:
      - "6500:5432"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    name: nest-prisma-docker-db