### GET
GET http://localhost:3000/lost-found
### GET BY ID
GET http://localhost:3000/lost-found/3
### POST
POST http://localhost:3000/lost-found
Content-Type: application/json

{ "item": "kalung", "characteristics": "emas", "status": "found", "location": "parkiran", "dateFound": "20230412", "dateRetrieved": "20230413" }
### DELETE
DELETE http://localhost:3000/lost-found/4
### PUT
PUT http://localhost:3000/lost-found/1
Content-Type: application/json

{ "item": "iPhone 13 Pro Max", "characteristic": "warna silver", "Status": "lost", "location": "" , "dateFound": "20230412", "dateRetrieved": "20230413" }
### PATCH
PATCH http://localhost:3000/lost-found/2

Content-Type: application/json
{ "status": "retrieved" }