
######## LOST AND FOUND API ===================================================================================
### GET (PUBLIC API)
GET http://localhost:3000/items

### GET BY ID (PUBLIC API)
GET http://localhost:3000/items/3

### POST (NEED AUTHENTICATION)
POST http://localhost:3000/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhaGEyQGVtYWlsLmNvbSIsInN1YiI6MTMsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NDQ4MjU4MiwiZXhwIjoxNjg0NTY4OTgyfQ.fSA5bG7cEf2PHrU71RP7sXVhanPKEuM7elpPPl6h_hE
Content-Type: application/json

{
  "item": "gelang 2",
  "characteristic": "emas",
  "status": "lost",
  "location": "mesjid",
  "dateFound": "2023-04-12",
  "dateRetrieved": "2023-04-13"
}

### PATCH (NEED AUTHENTICATION AND AUTHORIZATION)
PATCH http://localhost:3000/items/2
Content-Type: application/json

{
  "item": "baba"
}

### DELETE (NEED AUTHENTICATION AND AUTHORIZATION)
DELETE http://localhost:3000/items/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhaGEyQGVtYWlsLmNvbSIsInN1YiI6MTMsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NDQ4MjU4MiwiZXhwIjoxNjg0NTY4OTgyfQ.fSA5bG7cEf2PHrU71RP7sXVhanPKEuM7elpPPl6h_hE

######## USERS API ===================================================================================

### GET (NEED AUTHENTICATION)
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhaGEyQGVtYWlsLmNvbSIsInN1YiI6MTMsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NDQ4MjU4MiwiZXhwIjoxNjg0NTY4OTgyfQ.fSA5bG7cEf2PHrU71RP7sXVhanPKEuM7elpPPl6h_hE

### GET BY ID (NEED AUTHENTICATION)
GET http://localhost:3000/users/13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhaGEyQGVtYWlsLmNvbSIsInN1YiI6MTMsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NDQ4MjU4MiwiZXhwIjoxNjg0NTY4OTgyfQ.fSA5bG7cEf2PHrU71RP7sXVhanPKEuM7elpPPl6h_hE

### PATCH (NEED AUTHENTICATION AND AUTHORIZATION)
PATCH http://localhost:3000/users/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhaGEyQGVtYWlsLmNvbSIsInN1YiI6MTMsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NDQ4MjU4MiwiZXhwIjoxNjg0NTY4OTgyfQ.fSA5bG7cEf2PHrU71RP7sXVhanPKEuM7elpPPl6h_hE
Content-Type: application/json

{
  "email": "newgaga@email.com"
}

### DELETE (NEED AUTHENTICATION AND AUTHORIZATION)
DELETE http://localhost:3000/users/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhaGEyQGVtYWlsLmNvbSIsInN1YiI6MTMsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NDQ4MjU4MiwiZXhwIjoxNjg0NTY4OTgyfQ.fSA5bG7cEf2PHrU71RP7sXVhanPKEuM7elpPPl6h_hE

######## AUTH API ===================================================================================

### SIGN IN (PUBLIC API)

POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "haha2@email.com",
  "password": "12345"
}

### REGISTER (PUBLIC API)

POST http://localhost:3000/register
Content-Type: application/json

{
  "email": "haha2@email.com",
  "password": "12345"
}
